#!/usr/bin/env ruby
require File.expand_path(File.dirname(__FILE__) + '/shared')
BACKUP_DIR_ROOT = "/var/backups/mysql"
MAX_BACKUPS = 10

databases = `echo show databases | mysql`.strip.split("\n")
databases.shift
databases.delete("information_schema")
databases.delete("mysql")

now = Time.now.strftime("%Y-%m-%d-%H:%M:%S")
backup_dir = "#{BACKUP_DIR_ROOT}/#{now}"

sh "mkdir -p #{backup_dir}"
for database in databases
	sh "mysqldump #{database} | gzip --best | #{pv_or_cat} > #{backup_dir}/#{database}.sql.gz"
end

puts "Cleaning up..."
dirs = Dir["#{BACKUP_DIR_ROOT}/*"].sort.reverse
keep = dirs[0..MAX_BACKUPS]
delete = dirs - keep
delete.each do |dir|
	sh "rm -rf #{dir}"
end
sh "chmod -R o-rwx #{BACKUP_DIR_ROOT}"
