#!/usr/bin/env ruby
def help
	puts "Usage: deny <USERNAME> <DIR>"
	puts "Removes access for USERNAME to directory DIR."
	exit 1
end

def sh(command, *args)
	puts "#{command} #{args.join(' ')}"
	if !system(command, *args)
		STDERR.puts "*** ERROR"
		exit 1
	end
end

help if ARGV.size != 2
username, dir = ARGV
puts "cd #{dir}"
Dir.chdir(dir) do
	sh "setfacl -R -x user:#{username} ."
	sh "find -type d -print0 | xargs -0 -n 1000 -r setfacl -d -x user:#{username}"
end
