#!/usr/bin/env ruby
def help
	puts "Usage: permit <USERNAME> <DIR>"
	puts "Removes access for USERNAME to directory DIR."
	exit 1
end

def sh(command, *args)
	puts "#{command} #{args.join(' ')}"
	if !system(command, *args)
		STDERR.puts "*** ERROR"
		exit 1
	end
end

help if ARGV.size != 2
username, dir = ARGV
puts "cd #{dir}"
Dir.chdir(dir) do
	executable_files = "/tmp/executable-files.#{$$}"
	sh "find -type f -executable -print0 > #{executable_files}"
	sh "find -print0 | xargs -0 -n 1000 -r setfacl -x user:#{username}"
	sh "find -type d -print0 | xargs -0 -n 1000 -r setfacl -d -x user:#{username}"
	sh "find -type f -print0 | xargs -0 -n 1000 -r chmod -x"
	sh "cat #{executable_files} | xargs -0 -n 1000 -r chmod +x"
	sh "rm -f #{executable_files}"
end
