#!/usr/bin/env ruby
puts "Name                      Messages = Ready + Unack   Consumers   Memory (MB)"
puts "-------------------------------------------------------------------------------"
lines = `rabbitmqctl -q list_queues name messages messages_ready messages_unacknowledged consumers memory`
lines = lines.split("\n")
lines.each do |line|
	name, messages, ready, unack, consumers, memory = line.split(/[ \t]+/)
	messages = messages.to_i
	ready = ready.to_i
	unack = unack.to_i
	consumers = consumers.to_i
	memory = memory.to_i / 1024.0 / 1024
	printf("%-23s   %-8d = %-5d + %-5d   %-9d   %1.f\n", name, messages, ready, unack, consumers, memory)
end
