#!/bin/bash
CAPISTRANO_DIR=/u/apps
WWW_USER=www-data

export PATH="/tools:$PATH"

chmod -R g+w,o-rwx $CAPISTRANO_DIR
setfacl -m user:$WWW_USER:--x $CAPISTRANO_DIR
setfacl -d -m user:$WWW_USER:r-x $CAPISTRANO_DIR
for DIR in $CAPISTRANO_DIR/*; do
    # Give the web server read-only access to everything.
    # We tighten up permissions in later commands.
    permit $WWW_USER $DIR
    
    # Make the application directory itself executable-only
    # by the web server.
    if [[ -d $DIR/releases || -d $DIR/shared ]]; then
        setfacl -m user:$WWW_USER:--x $DIR
        setfacl -d -m user:$WWW_USER:--x $DIR
    fi
    
    # Make the 'releases' directory and immediate
    # subdirectories executable-only by the web server.
    if [[ -d $DIR/releases ]]; then
        setfacl -m user:$WWW_USER:--x $DIR/releases
        setfacl -m user:$WWW_USER:--x $DIR/releases/*
    fi
    
    # Deny web server access to the 'shared' directory.
    if [[ -d $DIR/shared ]]; then
        deny $WWW_USER $DIR/shared
        # If you store attachment files in the 'shared'
        # directory then you can allow only access to that:
        #
        # setfacl -m user:$WWW_USER:--x $DIR/shared
        # permit $DIR/shared/attachments
    fi
done
