#!/usr/bin/env ruby
# This script is automatically called in a cron job by root.
require 'etc'

DIRS = Dir[
	"/u/apps/**/.git"
]
DIRS.each do |dir|
	puts "# Garbage collecting #{dir}"
	Dir.chdir(dir) do
		stat = File.stat(dir)
		username = Etc.getpwuid(stat.uid).name
		command = "su -c 'git gc' #{username}"
		puts command
		if !system(command)
			abort "'git gc' failed"
		end
	end
	puts
end
