#!/usr/bin/env ruby
THRESHOLD=1000

warnings = []
`rabbitmqctl list_queues -q name messages`.split("\n").each do |line|
	name, messages = line.split(/[ \t]+/)
	messages = messages.to_i
	if messages > THRESHOLD
		warnings << "Queue '#{name}' has more than #{THRESHOLD} messages: #{messages}"
	end
end

if !warnings.empty?
	IO.popen("sendmail -t", "w") do |f|
		f.puts "To: info@phusion.nl"
		f.puts "From: noreply@unionstationapp.com"
		f.puts "Subject: [Union Station] Queue going out of control"
		f.puts
		f.puts warnings.join("\n")
	end
end
