#!/usr/bin/env ruby
def help
	puts "Usage: permit <USERNAME> <DIR> [--read-write]"
	puts "Give USERNAME read-only or read-write permission to directory DIR."
	puts "Default is read-only unless --read-write is given."
	exit 1
end

def sh(command, *args)
	puts "#{command} #{args.join(' ')}"
	if !system(command, *args)
		STDERR.puts "*** ERROR"
		exit 1
	end
end

help if ARGV.size != 2 && ARGV.size != 3
username, dir, read_write = ARGV
if read_write && read_write != "--read-write"
	STDERR.puts "*** Invalid option #{read_write}"
	help
end

puts "cd #{dir}"
Dir.chdir(dir) do
	executable_files = "/tmp/executable-files.#{$$}"
	sh "find -type f -executable -print0 > #{executable_files}"
	if read_write
		sh "find -type f -print0 | xargs -0 -n 1000 -r setfacl -m user:#{username}:rw-"
		sh "find -type d -print0 | xargs -0 -n 1000 -r setfacl -m user:#{username}:rwx"
		sh "find -type d -print0 | xargs -0 -n 1000 -r setfacl -d -m user:#{username}:rwx"
	else
		sh "find -type f -print0 | xargs -0 -n 1000 -r setfacl -m user:#{username}:r-"
		sh "find -type d -print0 | xargs -0 -n 1000 -r setfacl -m user:#{username}:r-x"
		sh "find -type d -print0 | xargs -0 -n 1000 -r setfacl -d -m user:#{username}:r-x"
	end
	sh "find -type f -print0 | xargs -0 -n 1000 -r chmod -x"
	sh "cat #{executable_files} | xargs -0 -n 1000 -r chmod +x"
	sh "rm -f #{executable_files}"
end
