#!/usr/bin/env ruby
require File.expand_path(File.dirname(__FILE__) + '/shared')
require 'optparse'

def parse_options
	options = {}
	parser = OptionParser.new do |opts|
		nl = "\n" + ' ' * 37
		opts.banner = "Usage: permit <USERNAME> <DIRECTORIES...> [options]"
		opts.separator "Give USERNAME read-only or read-write permission to the given directories."
		opts.separator ""
		
		opts.separator "Options:"
		opts.on("--read-write",
		        "Give read-write access. Default is#{nl}" +
		        "read-only unless this option is given.") do
			options[:read_write] = true
		end
	end
	begin
		parser.parse!
	rescue OptionParser::ParseError => e
		puts e
		puts
		puts "Please see '--help' for valid options."
		exit 1
	end

	if options[:help]
		puts parser
		exit
	elsif ARGV.size < 2
		puts parser
		exit 1
	else
		return options
	end
end

options = parse_options
username, *dirs = ARGV
dirs.each do |dir|
	print_activity "cd #{dir}"
	Dir.chdir(dir) do
		if options[:read_write]
			sh "setfacl -R -m user:#{username}:rwX ."
			sh "find -type d -print0 | xargs -0 -n 1000 -r setfacl -d -m user:#{username}:rwX"
		else
			sh "setfacl -R -m user:#{username}:r-X ."
			sh "find -type d -print0 | xargs -0 -n 1000 -r setfacl -d -m user:#{username}:r-X"
		end
	end
end
