#!/bin/bash
# Executes the given command, silencing all its output.
# Its output is only printed to STDERR if the command failed.

output="/tmp/output.$$"
"$@" >$output 2>&1
exit_code=$?
if [[ $exit_code != 0 ]]; then
	cat $output >&2
fi
rm -f $output
exit $exit_code
